---
src-ci-repo: https://github.com/SUSE/cf-ci.git

src-rails-example-repo: https://github.com/scf-samples/rails-example.git
kube-pool-repo: git@github.com:SUSE/cf-ci-pools.git
kube-pool-key: *github-private-key
kube-pool-branch: provo-kube-hosts
kube-pool-pool: provo-kube-hosts

s3-config-endpoint: ~
s3-config-access-key: *aws-access-key
s3-config-secret-key: *aws-secret-key
s3-config-bucket-opensuse: cap-release-archives
s3-config-prefix-opensuse: nightly/

s3-config-bucket-sles: cap-release-archives
s3-config-prefix-sles: nightly/

s3-config-prefix-sidecars: brokers/

registry-hostname: *docker-internal-registry
registry-username: *docker-internal-username
registry-password: *docker-internal-password
organization: splatform

magic-dns-service: omg.howdoi.website

src-repo: SUSE/scf
cap-sle-url: https://s3.amazonaws.com/cap-release-archives/master/scf-sle-2.15.2%2Bcf3.6.0.0.gde1bd02f.zip
cap-opensuse-url: https://s3.amazonaws.com/cap-release-archives/master/scf-opensuse-2.15.2%2Bcf3.6.0.0.gde1bd02f.zip

